Ignore failures on *-pc-windows-gnu
Ignore build/test failures on *-pc-windows-gnu due to upstream
toolchain issue.

Rust/gcc link fails with:
```
note: C:\projects\rust-jsonnet\target\x86_64-pc-windows-gnu\debug\build\jsonnet-sys-dab26afc938c47d5\out\libjsonnet.a(libjsonnet.o): In function `memory_panic':
      C:\projects\rust-jsonnet\jsonnet-sys/jsonnet/core/libjsonnet.cpp:40: undefined reference to `__imp___acrt_iob_func'
      C:\projects\rust-jsonnet\target\x86_64-pc-windows-gnu\debug\build\jsonnet-sys-dab26afc938c47d5\out\libjsonnet.a(libjsonnet.o): In function `jsonnet_evaluate_snippet_aux':
      C:\projects\rust-jsonnet\jsonnet-sys/jsonnet/core/libjsonnet.cpp:590: undefined reference to `__imp___acrt_iob_func'
```